language: ruby
rvm:
- 2.1.5
deploy:
  provider: heroku
  api_key:
    secure: Mqmb+bIj3BFSqLJTVjDTMNkNzsNPz3jZw2BOOSfv0+2XiVpW4CLpOdPqdZLKjBEp2nnP+peQok5M1gdvg7vY5s32BWed2UjRjdRBfDhgH/NyvksnyHmGtzkA2eh7zXPQ8WXY3QQfkyY9lySka4/wuX/DODUA0sVuondvP3Fchsg=
  app: isberlinhappytoday
  on:
    branch: master
    rvm: 2.1.5
sudo: false
